### ISSUE TITLE
Issue with agreement

### ISSUE THREAD

**Issue by MJGrey** [arismelachroinos/lscript#10]
It seems I'm stuck in a permanent loop in the part where I've got to type "YES". It spits out a line about an issue on line 3012 or something but its too fast to actually see where or what part is the issue.

**Comment by arismelachroinos** [comment]
What OS are you using ?

**Comment by MJGrey** [comment]
Ubuntu after ptf installed (so pretty much everything Kali has installed/both debian based). I'm busy reinstalling everything now to see whether that resolves the issue. I'll give a heads up as soon as I'm done.

**Comment by arismelachroinos** [comment]
I see. I installed ubuntu yesterday and i had the same problem. I will try to fix it as it seems simple, if you find something tell me.

**Comment by arismelachroinos** [comment]
For now, try the following:
1) Install the script with the following commands:
(if you haven't set a root password, type :  passwd root)
su root    (to enter the root password and gain root permissions to install the script)
cd /root
git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x install.sh
./install.sh
(then when that is done, open a new terminal and do the following)
su root
echo "I agree the terms" >> /root/lscript/IAGREE.txt
cd /bin/lscript
./l


however, if you type l in the terminal , you cannot access lscript , because ubuntu thinks you need to type ls and it lists the files in the current directory. So until i find a better solution, you need to access it via:
su root
cd /bin/lscript
./l


OR


su root
bash /bin/lscript/l

**Comment by MJGrey** [comment]
Ok, it still doesn't run on my ubuntu distro but I've tested it on Parrot OS and that worked just fine. Right now, I did all the things it wanted as well as finally got through to the part where it wants me to Agree but beyond that its just stuck. Thanks anyway!

**Comment by arismelachroinos** [comment]
well for this issue there are 2 possible causes.
You should type   su root      and then type your pass, and then type echo "I agree" > /root/lscript/IAGREE. txt
Then, if this is successful, then the only possible cause is that you need to type   su root    before executing the script. so you should open a new terminal and type
su root
cd /bin/lscript
. /l

it worked for me so please try again and report.

**Comment by arismelachroinos** [comment]
echo "I agree" > /root/lscript/IAGREE.txt    **

**Comment by MJGrey** [comment]
Fixed :)
