### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ekultek** [arismelachroinos/lscript#20]
If your script is suppose to make things easier, why is there so much that has to be done to install a tool? Why don't you have flags that can be passed to the script in order for it to install a certain tool without having to launch the terminal part of it?

**Comment by arismelachroinos** [comment]
Is there a lot being done to install a tool? Are you talking about a specific tool? Well i just made it out of what i found o every script's github page. I don't think thats a big deal since you only install them once, but if you have time tell me to which tools are you referring.

**Comment by Ekultek** [comment]
I'm just saying, it says this script is suppose to make things easier, but it makes some things more complicated, you have to find the tool in your list, when 99% of the time you can just do a `sudo apt-get install <package>`. Not bashing it, just saying you should add some flags so that when someone knows what they wanna install, they can do it quickly. For example:

`l install pupy` to install Pupy, or `l install nmap` for nmap.

Instead of just jumping to the console right off the bat. That would make it easier, and faster.

**Comment by arismelachroinos** [comment]
It's all in menus and it's personal preference, I find it very fast to select a number with the name of the tool than trying to find exactly the name to write it, and I don't really like flags, that's why I have made some automated subscripts for tools with flags like yours . I thing now it is more user friendly and once you get used to the menus then it's going to be super fast. one thing that will be usefull would be to sort the tools alphabetically, but I will have to change all numbers every time I add a new tool. I will consider having the option to install the tool you want to launch and is not installed already, instead of having to go back to the installation menu and find the tool to install it.   thanks for the recommendation though

**Comment by Ekultek** [comment]
Well, you could also, instead of having to change all the numbers, write a list of tools that are already implemented, and a range from 1 to the length of the list, that way when you need to add a new tool, you just add it to the list instead of changing all the numbers. So for example:

```
baal@baal-Aspire-5733Z:~$ TOOL_ARRAY=("pupy" "nmap" "dagon")
baal@baal-Aspire-5733Z:~$ LEN_TOOLS=${#TOOL_ARRAY[@]}
baal@baal-Aspire-5733Z:~$ seq ${LEN_TOOLS}
1
2
3
baal@baal-Aspire-5733Z:~$ 
```

So now if I want to change this, all I have to do is add to the `TOOL_ARRAY`:
```
baal@baal-Aspire-5733Z:~$ TOOL_ARAY=("pupy" "nmap" "dagon" "another tool" "and one more")
baal@baal-Aspire-5733Z:~$ LEN_TOOLS=${#TOOL_ARRAY[@]}
baal@baal-Aspire-5733Z:~$ seq ${LEN_TOOLS}
1
2
3
4
5
baal@baal-Aspire-5733Z:~$ 
```

**Comment by arismelachroinos** [comment]
Installation now can be done when launching a tool that is not installed.
