### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ph1l0u1ll3** [arismelachroinos/lscript#25]
Hello,

I'm trying to install lazy script on Backbox 5.0 (Ubuntu 16.04.1 based distro with kernel 4.10.0-32-generic & XFCE as Windows Manager) and I'm following strictly all the steps described here, but it fails with this (in French):

```
./install.sh: ligne 130: [: = : opérateur unaire attendu
Open a NEW terminal and type 'l' to launch the script
./install.sh: ligne 139: gnome-terminal: commande introuvable
```

Very weird as lscript/install.sh has only 107 line!

Of course, when I'm trying to launch the script via the 'l' command, I'm having this:
`commande introuvable`

**Comment by arismelachroinos** [comment]
Okay, so maybe it is my fault and i need to make it more clear, this is only ment to work on Kali Linux. Why? Because this is what i have installed and i am pretty happy with that. I am so sorry about that, it would be awesome to make it work for all distros but i cannot do it, there are tons of things to be changed and i dont have the time and patience for starting from scratch again. Sorry again.

**Comment by Ekultek** [comment]
You do know that Kali and Ubuntu are based on the same distro right? The only thing that would really need to be changed is the script init after installation, and the force directory installation for root. And btw having Kali Linux as your main operating system is an awful idea and you need to not do that..

**Comment by arismelachroinos** [comment]
Of course i know that, I tried to make changes to make it work on Ubuntu and I decided I won't because its as simple as you think, First of all just changing the 'l' to something like 'u' worked, yes. Ubuntu users however need to always be root users to run it. they need to execute ' su root' every time before they execute the script. And lets say that's ok too, but lscript calls many other subscripts (e.g. handshake , WPS , deauth....) that they also need to be run as root in order to work . Well , you cant do that from within a script. When a new terminal is called to run a script, you cannot make it to run as root from within a script. At least i didnt find a way to do that. And lets say that this can be fixed too, well many other tools that i included in the installation are not supported by Ubuntu as well! ( e.g. wifiphisher) . And to be even more honest , Ubuntu is not designed for pentesting at all. So please dont just say its easy to port, if it was easy i would not say no . I would really like more users to use the script of course.And i never said that kali is my main OS. I run it in a virtual machine . I only said that I have only kali installed . Not Ubuntu , not mint , not blackbox.
