### ISSUE TITLE
Lazyscript on Cyborg Essential (Debian)

### ISSUE THREAD

**Issue by nazarj** [arismelachroinos/lscript#35]
Hello, first thank you for the amazing work.

I use Cyborg Essential mainly because it is very fast on low spec laptop, has stability, many great tools and scripts, and is debian based which mean i can use kali-related tool.

Lazy script install fine on the distro, i can't use "l" as a shortcut though i have to type : 

"cd lscript
./l"

I can install tools, some works but many don't, because when i install them, it tell me at the end when i launch them that some requirement aren't installed, prompt me to install it, i do it but nothing happen and the error come back.

I also have on certains tool that are completly installed this error when i launch it "tcpdump is not installed, check PATH) or something like that i wrote the important part.

What do you think about it ? I know that modifying the script to make it work on Ubuntu or Arch would be a pain, but since Cyborg Essential is Debian-based, do you think it is solvable ? Thank you in advance no matter the answer, and i would like your opinion on Cyborg Essential if you ever try it.

**Comment by arismelachroinos** [comment]
Thanks a lot for your kindness. I am sorry I cannot modify the script to other distros, because : 
1) There are tons of thing that need to be changed and is different for every distro.

2) I only work with kali. This doesnt mean that kali is better than your distro but it just means that I got used to it , and installing a new distro and learning it and adding support to it isnt going to happen in the near future. Because i tried with Ubuntu and i gave up due to the many things that needed to be changed and I cannot test it on every update there too.

3) Some tools that are included within lscript are not supported by other distros too. So I can not add a tool if every distro is supported. I cannot test that every time

4) I am alone here and i like it that way. I dont have that much time for all that. I am 19 years old and i am studing for Audio and Visual arts. Scripting is not my main thing, i really like it though. It is just for my free time.

I am really sorry that you cannot use the script, I really want more and more people to work faster with less commands with this all-in-one tool .

**Comment by nazarj** [comment]
Thank you for the fast answer, don't mind about the distro i will simply use kali linux if it is the most conveniant.

Now i understand why you made the script, since you have little time, better to use it for action only instead of preparing your workshop and then youre already out of time.

Will look forward your next updates/works.
