### ISSUE TITLE
Not Running Kali

### ISSUE THREAD

**Issue by synkoptik** [arismelachroinos/lscript#69]
Is there a work around for those of us no running Kali.. cause that would suck if we're forced to run Kali in order to be lazier.

**Comment by arismelachroinos** [comment]
There is not. There are tons of things to be changed for every single OS so yeah it sucks for those who are not already in Kali. Sorry for that, I do not have the time and patience to do that, I tried with Ubuntu and I gave up. Ubuntu does not even focus on penetration testing. I made it for Kali because thats just what I use. And Kali is not that heavy, you can drop it on the VM and test this and if you dont like it just delete it.Thats all I can do.

**Comment by synkoptik** [comment]
Thanks arismelachroinos for responding and for creating this script.  

I actually took a look inside the scripted and realized that the possible reason was because of the way you structured the "calling" (for lack of better words) of thes files.  What I mean is that the script looks at /root/scripts or something rather.  The point is that if I SU (Switch User) to root (SuperUser) then the script works fine.  

I am using Deepin 15.5 an Ubuntu fork.

Thanks again arsmelachroinos!  I love it!
